---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user
  namespace: team-sock-shop
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: user

  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
    
